### ISSUE TITLE
minor logging bug on pushing button

### ISSUE THREAD

**Issue by stormvsn** [Sirawit7205/ktaneScrew#1]
The debug statement on pushing a button uses the button pushed instead of the module ID; that is, it generates a message like:
`[Screw #B] Pushed button B at 2, expected B at 2.`
Instead of:
`[Screw #1] Pushed button B at 2, expected B at 2.`

Should just be a matter of changing the appropriate line (currently https://github.com/Sirawit7205/ktaneScrew/blob/master/Assets/screw.cs#L308 ) to include `[Screw #{0}]` instead of `[Screw #{1}]`.

**Comment by Sirawit7205** [comment]
Thanks, I fixed it.
